/*
 * This file is generated by jOOQ.
 */
package com.okeicalm.simpleJournalEntry;


import com.okeicalm.simpleJournalEntry.tables.JournalEntries;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in simple_journal_entry_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index JOURNAL_ENTRIES_FK_ACCOUNT = Internal.createIndex(DSL.name("fk_account"), JournalEntries.JOURNAL_ENTRIES, new OrderField[] { JournalEntries.JOURNAL_ENTRIES.ACCOUNT_ID }, false);
    public static final Index JOURNAL_ENTRIES_FK_JOURNAL = Internal.createIndex(DSL.name("fk_journal"), JournalEntries.JOURNAL_ENTRIES, new OrderField[] { JournalEntries.JOURNAL_ENTRIES.JOURNAL_ID }, false);
}
