/*
 * This file is generated by jOOQ.
 */
package com.okeicalm.simpleJournalEntry;


import com.okeicalm.simpleJournalEntry.tables.Accounts;
import com.okeicalm.simpleJournalEntry.tables.records.AccountsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * simple_journal_entry_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountsRecord> KEY_ACCOUNTS_CODE = Internal.createUniqueKey(Accounts.ACCOUNTS, DSL.name("KEY_accounts_code"), new TableField[] { Accounts.ACCOUNTS.CODE }, true);
    public static final UniqueKey<AccountsRecord> KEY_ACCOUNTS_PRIMARY = Internal.createUniqueKey(Accounts.ACCOUNTS, DSL.name("KEY_accounts_PRIMARY"), new TableField[] { Accounts.ACCOUNTS.ID }, true);
}
