/*
 * This file is generated by jOOQ.
 */
package com.okeicalm.simpleJournalEntry;


import com.okeicalm.simpleJournalEntry.tables.Accounts;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SimpleJournalEntryDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>simple_journal_entry_db</code>
     */
    public static final SimpleJournalEntryDb SIMPLE_JOURNAL_ENTRY_DB = new SimpleJournalEntryDb();

    /**
     * The table <code>simple_journal_entry_db.accounts</code>.
     */
    public final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * No further instances allowed
     */
    private SimpleJournalEntryDb() {
        super("simple_journal_entry_db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Accounts.ACCOUNTS
        );
    }
}
