/*
 * This file is generated by jOOQ.
 */
package com.okeicalm.simpleJournalEntry;


import com.okeicalm.simpleJournalEntry.tables.Accounts;
import com.okeicalm.simpleJournalEntry.tables.JournalEntries;
import com.okeicalm.simpleJournalEntry.tables.Journals;
import com.okeicalm.simpleJournalEntry.tables.Users;


/**
 * Convenience access to all tables in simple_journal_entry_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>simple_journal_entry_db.accounts</code>.
     */
    public static final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>simple_journal_entry_db.journal_entries</code>.
     */
    public static final JournalEntries JOURNAL_ENTRIES = JournalEntries.JOURNAL_ENTRIES;

    /**
     * The table <code>simple_journal_entry_db.journals</code>.
     */
    public static final Journals JOURNALS = Journals.JOURNALS;

    /**
     * The table <code>simple_journal_entry_db.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
