/*
 * This file is generated by jOOQ.
 */
package com.okeicalm.simpleJournalEntry;


import com.okeicalm.simpleJournalEntry.tables.Users;


/**
 * Convenience access to all tables in simple_journal_entry_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>simple_journal_entry_db.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
