/*
 * This file is generated by jOOQ.
 */
package com.okeicalm.simpleJournalEntry.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Journals implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long      id;
    private final LocalDate incurredOn;

    public Journals(Journals value) {
        this.id = value.id;
        this.incurredOn = value.incurredOn;
    }

    public Journals(
        Long      id,
        LocalDate incurredOn
    ) {
        this.id = id;
        this.incurredOn = incurredOn;
    }

    /**
     * Getter for <code>simple_journal_entry_db.journals.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>simple_journal_entry_db.journals.incurred_on</code>.
     */
    public LocalDate getIncurredOn() {
        return this.incurredOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Journals (");

        sb.append(id);
        sb.append(", ").append(incurredOn);

        sb.append(")");
        return sb.toString();
    }
}
